import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { PROCESSING_STEPS, SAMPLE_RATE } from "./audio";
import type { Cue, Project, Take } from "./types";

const ROOT = "res://cuebound_pack";
const EVENT_ID = /^[a-z][a-z0-9_]*$/;
const sha256 = (b: string | Uint8Array) => new Bun.CryptoHasher("sha256").update(b).digest("hex");

const tres = (paths: string[]) =>
  `[gd_resource type="AudioStreamRandomizer" load_steps=${paths.length + 1} format=3]\n\n` +
  paths.map((p, i) => `[ext_resource type="AudioStream" path="${ROOT}/${p}" id="${i + 1}"]\n`).join("") +
  `\n[resource]\nstreams_count = ${paths.length}\n` +
  paths.map((_, i) => `stream_${i}/stream = ExtResource("${i + 1}")\nstream_${i}/weight = 1.0\n`).join("");

const script = (ids: string[]) => `extends Node
# Generated by CueBound. Autoload this script as "Sfx", then call Sfx.play("event_id").

const STREAMS := {
${ids.map((id) => `\t"${id}": preload("${ROOT}/${id}.tres"),\n`).join("")}}

var _players := {}
var _warned := {}


func _ready() -> void:
\tfor id in STREAMS:
\t\tvar player := AudioStreamPlayer.new()
\t\tplayer.stream = STREAMS[id]
\t\tplayer.max_polyphony = 8
\t\tadd_child(player)
\t\t_players[id] = player


func play(event_id: String) -> void:
\tif _players.has(event_id):
\t\t_players[event_id].play()
\telif not _warned.has(event_id):
\t\t_warned[event_id] = true
\t\tpush_warning("CueBound: no sound for event \\"%s\\"" % event_id)
`;

const hookup = (ids: string[], incomplete: { eventId: string; accepted: number; required: number }[]) => `# Connect this sound pack

1. Copy the \`cuebound_pack/\` folder into your Godot project root, next to \`project.godot\`.
2. In Project > Project Settings > Globals > Autoload, add \`${ROOT}/cuebound_sfx.gd\` with the name \`Sfx\`.
3. Call \`Sfx.play("jump")\` in your own code at the moment the action happens, for example right after you set the jump velocity.

Importing the pack does not connect sounds to your game. A sound plays only where you add a call.

Sounds generated with the Livepeer Agent network, model Mirelo SFX 1.6 (Mirelo AI), then trimmed and levelled by CueBound. Credit "Sound effects powered by Mirelo AI" if you ship them, and check Mirelo's terms (https://mirelo.ai/terms) for your use.

Events: ${ids.map((id) => `\`${id}\``).join(", ") || "none"}.
${incomplete.length ? `\nIncomplete: ${incomplete.map((c) => `\`${c.eventId}\` (${c.accepted} of ${c.required} accepted takes)`).join(", ")}. An event with no sound does nothing and prints one warning.\n` : ""}`;

export async function exportPack({ project, cues, takes, outDir }: { project: Project; cues: Cue[]; takes: Take[]; outDir: string }) {
  const dir = join(outDir, "cuebound_pack");
  await rm(dir, { recursive: true, force: true });
  await mkdir(join(dir, "audio"), { recursive: true });

  const files: { path: string; sha256: string }[] = [];
  const put = async (path: string, data: string | Uint8Array) => {
    await writeFile(join(dir, path), data);
    files.push({ path, sha256: sha256(data) });
  };

  const events: Record<string, unknown> = {};
  const incomplete: { eventId: string; accepted: number; required: number }[] = [];
  const sorted = [...cues].sort((a, b) => (a.eventId < b.eventId ? -1 : a.eventId > b.eventId ? 1 : 0));
  for (const [i, cue] of sorted.entries()) {
    if (!EVENT_ID.test(cue.eventId)) throw new Error(`invalid eventId "${cue.eventId}": use a-z, 0-9 and _`);
    if (sorted[i - 1]?.eventId === cue.eventId) throw new Error(`duplicate eventId "${cue.eventId}"`);
    const accepted = takes.filter((t) => t.cueId === cue.id && t.status === "accepted");
    const required = cue.recurring ? 2 : 1;
    if (accepted.length < required) incomplete.push({ eventId: cue.eventId, accepted: accepted.length, required });
    if (!accepted.length) continue;

    const paths: string[] = [];
    for (const [n, take] of accepted.entries()) {
      if (!take.finalPath) throw new Error(`accepted take ${take.id} has no rendered file`);
      const bytes = await readFile(take.finalPath);
      if (take.sha256 && take.sha256 !== sha256(bytes)) throw new Error(`take ${take.id}: ${take.finalPath} does not match its recorded sha256`);
      const path = `audio/${cue.eventId}_${n + 1}.wav`;
      await put(path, bytes);
      paths.push(path);
    }
    await put(`${cue.eventId}.tres`, tres(paths));
    const { trimStartMs, maxDurationMs, fadeOutMs, gainDb } = cue.processing;
    events[cue.eventId] = {
      resource: `${ROOT}/${cue.eventId}.tres`,
      recurring: cue.recurring,
      takes: paths,
      processing: { trimStartMs, maxDurationMs, fadeOutMs, gainDb },
    };
  }

  const ids = Object.keys(events);
  await put("cuebound_sfx.gd", script(ids));
  await put("HOOKUP.md", hookup(ids, incomplete));
  const manifest = {
    schema: "cuebound-pack/1",
    project: project.name,
    intendedUse: `One-shot sound effects for the 2D Godot 4 game "${project.name}". Each event is an AudioStreamRandomizer that your own code plays with Sfx.play(eventId); see HOOKUP.md.`,
    godot: { installPath: `${ROOT}/`, autoload: { name: "Sfx", path: `${ROOT}/cuebound_sfx.gd` } },
    audio: { container: "wav", codec: "pcm_s16le", sampleRate: SAMPLE_RATE, channels: 1, processing: PROCESSING_STEPS },
    generator: { network: "Livepeer Agent", capability: "mirelo-sfx", model: "Mirelo-AI/sfx1.6/text-to-audio", attribution: "Sound effects powered by Mirelo AI", terms: "https://mirelo.ai/terms" },
    events,
    incomplete,
    files: [...files].sort((a, b) => (a.path < b.path ? -1 : 1)),
  };
  await put("manifest.json", JSON.stringify(manifest, null, 2) + "\n");

  return { dir, files, incomplete: incomplete.map((c) => c.eventId) };
}
